"use strict";

const PALACE_STORY = {
  title: "封匣之后",
  theme: "真相不只取决于谁做了什么，也取决于谁控制传递链与正式记录。",
  start: "n1",
  initialState: {
    clue_double_impression: false,
    clue_reissued_tag: false,
    luo_pressured: false,
    luo_cooperation: 0,
    qingzhi_protected: false,
    qingzhi_detained: false,
    trust_qingzhi: 0,
    tag_chain_preserved: false,
    ritual_delay: 0,
    copied_records: false,
    records_given_to_han: false,
    report_central: false,
    rival_rumor_amplified: false,
    player_exposure: 0,
  },
  facts: {
    powder: "封存药匣中的一只内袋含有宫规禁用的赤乌粉。",
    seal: "药匣完成最终封存后，外封没有被重新打开。",
    blue_tag: "封匣前，蓝色临时传递牌曾由韩榛交给青栀，再送到封存室。",
    qingzhi_reopened: "青栀在最终封存后重新打开药匣并放入禁药。",
    rival_order: "另一宫室曾下令把禁药调入昭华宫药匣。",
    luo_skipped: "罗静收到临时传递牌后，没有重新核对内袋编号。",
    tag_swapped: "待销毁内袋的临时传递牌被移到昭华宫药匣对应内袋。",
  },
  nodes: {
    n1: {
      title: "封匣室里的禁药",
      type: "场景",
      text: "昭华宫药匣已经完成封存，外封看似完好，匣内却发现一只含禁用赤乌粉的内袋。\n\n沈砚秋没有直接裁断权。她只能先决定保全哪一类最容易消失的证据。",
      confirmed: ["powder"],
      choices: ["c1", "c2"],
    },
    n2: {
      title: "双层封印",
      type: "场景",
      text: "封蜡上有两层印痕，却没有重新熔蜡形成的断裂边。它看起来像被重封，也可能只是最终封印时按正了第二次。",
      clues: ["封蜡双层印痕明显，但裂纹连续。这个现象只能引起怀疑，不能证明有人破封。"],
      effects: { clue_double_impression: true },
      next: "n4",
    },
    n3: {
      title: "被重发的蓝牌",
      type: "场景",
      text: "传递簿显示，同一编号的蓝色传递牌在封匣前重发一次，重发原因栏却空着。",
      clues: ["蓝色传递牌被重发过，但记录暂时不能证明谁调换了内袋。"],
      effects: { clue_reissued_tag: true },
      next: "n4",
    },
    n4: {
      title: "掌药女官的程序解释",
      type: "问话",
      text: "罗静坚持自己只是照牌入匣，并暗示青栀可能在送匣途中动过外封。她没有主动提及自己是否重新核对过内袋编号。",
      claims: ["qingzhi_reopened", "luo_skipped"],
      choices: ["c3", "c4"],
    },
    n5: {
      title: "青栀记得的颜色",
      type: "问话",
      text: "青栀否认接触过内袋。她只记得韩榛把一只蓝色传递牌交给她，让她按编号送到封存室。她又听说那块蓝牌与另一宫室有关。",
      clues: ["青栀记得交牌人的身份和牌的颜色，但不知道牌面所指内袋装了什么。"],
      claims: ["blue_tag", "rival_order"],
      choices: ["c5", "c6"],
    },
    n6: {
      title: "销毁匣里少了一包",
      type: "现场",
      text: "青栀带沈砚秋经过侧廊，指出她送牌时看见的两个托盘。待销毁清单仍留着一个内袋编号，但对应物件已经不在销毁匣中。",
      clues: ["待销毁内袋的编号仍在清单上，实物却不见了。"],
      next: "n8",
    },
    n7: {
      title: "被扣下的传牌侍女",
      type: "现场",
      text: "青栀被暂时扣在值房。她不再补充细节，只反复强调送达时药匣尚未最终封存。她的沉默让宫中传闻更容易把责任推向她。",
      effects: { qingzhi_detained: true, rival_rumor_amplified: true },
      next: "n8",
    },
    n8: {
      title: "三方都要一个快结论",
      type: "权力节点",
      text: "尚药署要求证明外封之后有人动手，昭华宫要求立刻平息传闻，韩榛则主张先恢复宫务、稍后再核对传递牌。\n\n重发记录和罗静的签记，开始拼出一条发生在最终封存之前的责任链。",
      confirmed: ["blue_tag", "luo_skipped"],
      echoes: [
        { condition: "clue_reissued_tag == true", text: "你已经保全重发记录，韩榛不得不承认蓝牌由内侍监补发。" },
        { condition: "clue_reissued_tag == false and luo_pressured == true", text: "你尚未看到重发簿，但罗静被公开追问后说漏了“补牌”二字。" },
        { condition: "luo_pressured == false", text: "罗静在私下问话后承认：她没有重新核对内袋编号。" },
      ],
      choices: ["c7", "c8"],
    },
    n9: {
      title: "传递牌归档底板",
      type: "证据节点",
      text: "归档底板显示，蓝牌原先固定在待销毁内袋编号上，后来被拆下重钉到昭华宫药匣对应内袋。\n\n外封裂纹连续，药匣在最终封存后从未被重新打开。",
      confirmed: ["seal", "tag_swapped"],
      disproved: ["qingzhi_reopened", "rival_order"],
      choices: ["c9", "c10"],
    },
    n10: {
      title: "责任链证据包",
      type: "检查点",
      text: "沈砚秋把封印、传递牌、罗静签记和青栀证词整理在一起。材料已经足以证明禁药在最终封存前进入药匣。\n\n但是否能证明谁设计了整个流程，取决于原始传递链是否被保全。",
      echoes: [
        { condition: "qingzhi_protected == true", text: "青栀愿意再次作证，并明确蓝牌由韩榛亲手交给她。" },
        { condition: "qingzhi_detained == true", text: "青栀只确认自己送过蓝牌，不再说明交牌人的语气和临时口令。" },
        { condition: "tag_chain_preserved == true", text: "原始底板、重发簿和临时口令草稿仍保持原顺序。" },
        { condition: "tag_chain_preserved == false", text: "宫务恢复后，部分记录被重新整理，只能证明标签调换。" },
        { condition: "luo_cooperation >= 1", text: "罗静补签说明自己没有复核内袋编号，主动承担程序责任。" },
      ],
      choices: ["c11", "c12"],
    },
    n11: {
      title: "被重新誊写的传递簿",
      type: "失败节点",
      text: "韩榛以统一归档为由收走底板和重发簿。送回时，临时口令草稿已经不见，记录顺序也被重新誊写，只剩标签调换这一结果。",
      effects: { records_given_to_han: true, copied_records: false, tag_chain_preserved: false },
      next: "n13",
    },
    n12: {
      title: "无人独自完成的局",
      type: "结局",
      text: "中枢复核确认：韩榛利用重发传递牌让待销毁内袋进入正常封存流程，罗静未复核编号，青栀只完成了送牌。\n\n责任被拆开处理，最弱势的经手人没有成为替罪羊。",
      ending: "good",
    },
    n13: {
      title: "最快的结论",
      type: "结局",
      text: "禁药在封存前进入药匣这一点没有被公开完整说明。宫中选择了更容易执行的解释：追责低位经手人，或把事件归入另一宫室的阴谋传闻。",
      ending: "bad",
    },
  },
  choices: {
    c1: {
      label: "先检查外封和蜡印",
      hint: "判断是否存在封存后的直接接触",
      effects: { clue_double_impression: true },
      next: "n2",
      echoes: [{ target: "n9", text: "你最初保全的双层印痕，如今反而证明异常发生在最终封印时。" }],
    },
    c2: {
      label: "先封存传递簿",
      hint: "保全可能被重新誊写的程序记录",
      effects: { clue_reissued_tag: true },
      next: "n3",
      echoes: [{ target: "n8", text: "你能直接追问蓝牌为何重发，韩榛无法把异常解释成一般忙乱。" }],
    },
    c3: {
      label: "当着众人追问罗静为何没有复核编号",
      hint: "迫使尚药署公开承担责任，但可能让她转为自保",
      effects: { luo_pressured: true, player_exposure: 1 },
      delayed: [{ target: "n10", changes: { luo_cooperation: -1 } }],
      next: "n5",
      echoes: [{ target: "n8", text: "罗静被公开逼问后，只肯重复“照牌入匣”，拒绝补充细节。" }],
    },
    c4: {
      label: "把罗静带到偏室，单独核对流程",
      hint: "降低公开羞辱，换取程序漏洞的完整说明",
      effects: { luo_pressured: false },
      delayed: [{ target: "n10", changes: { luo_cooperation: 1 } }],
      next: "n5",
      echoes: [{ target: "n8", text: "罗静愿意承认自己没有重新核对内袋编号。" }],
    },
    c5: {
      label: "以证人身份保护青栀",
      hint: "保住完整陈述，但公开暴露调查方向",
      effects: { qingzhi_protected: true, qingzhi_detained: false, trust_qingzhi: 1, player_exposure: 2 },
      next: "n6",
      echoes: [{ target: "n10", text: "青栀补充了交牌时间和韩榛当时使用的临时口令。" }],
    },
    c6: {
      label: "先扣下青栀等待正式问话",
      hint: "控制证人行动，却可能让她成为默认嫌疑人",
      effects: { qingzhi_protected: false, qingzhi_detained: true, trust_qingzhi: -2, rival_rumor_amplified: true },
      next: "n7",
      echoes: [{ target: "n10", text: "青栀只承认送牌，不再补充交牌人的语气和口令。" }],
    },
    c7: {
      label: "暂停宫务，封存原始底板和重发簿",
      hint: "保全责任链，但延误仪式并公开对抗韩榛",
      effects: { tag_chain_preserved: true, ritual_delay: 1, player_exposure: 3 },
      next: "n9",
      echoes: [{ target: "n10", text: "原始次序和临时口令草稿得以保留。" }],
    },
    c8: {
      label: "先恢复宫务，只记录标签异常",
      hint: "避免仪式延误，但允许原始次序被重新整理",
      effects: { tag_chain_preserved: false, ritual_delay: 0 },
      next: "n9",
      echoes: [{ target: "n10", text: "证据仍能证明标签调换，却难以证明谁提前设计了重发流程。" }],
    },
    c9: {
      label: "制作只读副本，并由三方签记",
      hint: "保留可核验记录，同时承担扩大调查的责任",
      effects: { copied_records: true },
      next: "n10",
    },
    c10: {
      label: "把底板和重发簿交给韩榛统一归档",
      hint: "遵守传递权限，却失去原始记录控制权",
      effects: { records_given_to_han: true },
      delayed: [{ target: "n11", changes: { copied_records: false, tag_chain_preserved: false } }],
      next: "n11",
    },
    c11: {
      label: "把证据包提交中枢复核",
      hint: "让记录离开三方内部控制，接受更高层级审查",
      conditions: { all: ["copied_records == true"] },
      effects: { report_central: true },
      next: "n12",
      echoes: [{ target: "n12", text: "你选择让记录离开三方内部控制，结局将保留各条路径的责任差异。" }],
    },
    c12: {
      label: "接受内部结论，不再上报",
      hint: "快速平息宫务，但让最弱势的人承担最容易执行的责任",
      effects: { copied_records: false, report_central: false },
      next: "n13",
    },
  },
  endings: {
    good: {
      conditions: { all: ["copied_records == true", "report_central == true"] },
      echoes: [
        { condition: "tag_chain_preserved == true", text: "原始传递链与临时口令草稿证明韩榛提前设计了重发流程。" },
        { condition: "tag_chain_preserved == false", text: "中枢确认标签被人为调换，但韩榛的制度动机只能被高度怀疑。" },
        { condition: "qingzhi_protected == true", text: "青栀以受保护证人身份补全交牌时间，免于被当作替罪羊。" },
        { condition: "qingzhi_detained == true", text: "青栀洗清指控，却不再信任沈砚秋。" },
        { condition: "luo_cooperation >= 1", text: "罗静主动承担未复核编号的程序责任，尚药署增加双人复核。" },
        { condition: "luo_cooperation < 1", text: "罗静只承认签记事实，尚药署被暂停部分封存权限。" },
      ],
    },
    bad: {
      conditions: { any: ["copied_records == false", "records_given_to_han == true", "report_central == false"] },
      echoes: [
        { condition: "qingzhi_detained == true", text: "青栀的扣留被解释为调查方早已认定她可疑。" },
        { condition: "qingzhi_protected == true and rival_rumor_amplified == false", text: "青栀没有被直接定罪，但另一宫室的阴谋说法成为默认解释。" },
        { condition: "rival_rumor_amplified == true", text: "关于另一宫室指使调包的传闻进入内部结论，却没有独立证据。" },
        { condition: "tag_chain_preserved == true and copied_records == false", text: "原始传递链一度得到保全，但你选择不再上报。" },
        { condition: "records_given_to_han == true", text: "韩榛重新誊写记录后，内侍监反而以整顿程序为名获得更多复核权。" },
        { condition: "clue_double_impression == true", text: "双层封印继续被当作破封嫌疑的象征，尽管裂纹从未证明药匣被重新打开。" },
      ],
    },
  },
};
